#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp $TMPDIR/echo-resource-resource-request.XXXXXX)

cat > $payload <&0

uri=$(jq -r '.source.uri // ""' < $payload)
uri_config=$(jq -r '.source.uri_config // ""' < $payload)
branch=$(jq -r '.source.branch // ""' < $payload)
destination=$TMPDIR/echo-resource-resource-repo-cache

branchflag=""
git_hash=""
if [ -n "$branch" ]; then
  branchflag="--branch $branch"
fi

if [ -d $destination ]; then
  cd $destination
  git fetch origin
  git reset --hard origin/master
else
  git clone --single-branch $uri_config $branchflag $destination
  cd $destination
fi

git_hash=$(git rev-parse HEAD | jq -R .)

echo "{\"version\":\"$git_hash\"}" | jq --slurp . >&3