#!/bin/bash

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp $TMPDIR/echo-resource-resource-request)

cat > $payload <&0

uri=$(jq -r '.source.uri // ""' < $payload)
uri_config=$(jq -r '.source.uri_config // ""' < $payload)
branch=$(jq -r '.source.branch // ""' < $payload)
destination=$TMPDIR/echo-resource-resource-repo-cache
branchflag=""
if [ -n "$branch" ]; then
  branchflag="--branch $branch"
fi

if [ -d $destination ]; then
  cd $destination
  git fetch
  git reset --hard FETCH_HEAD
else
  cd $destination
  git clone --single-branch $uri_config $branchflag $destination
  cd ..
fi

check_version >&3